stages:
  - lint
  - test
  - deploy

lint:
  image: instrumentisto/flutter:3.24.0
  stage: lint
  script:
    - flutter analyze

tests:
  needs:
    - lint
  image: instrumentisto/flutter:3.24.0
  stage: test
  script:
  - flutter test

build-ios-ipa:
  needs:
    - tests
    - lint
  image: sickcodes/docker-osx:naked
  stage: deploy
  script:
    - echo test

